### ISSUE TITLE
Were you aware of the existing Flash Cards front-end app ?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/SwordSandBox#3]
The SWORD Developers’ wiki mentions that there’s a Flash Cards front-end app from the earlier days of CrossWire.

I think it was developed by Troy.

I’ve not seen it mentioned in any mailing list in the last decade or so.

**Comment by pierre-amadio** [comment]
I saw mention about it but never used it (nor do i know where to find it).
As far as flashcard are concerned, I used anki and build some deck based on some sword module + strong dictionnary for vocabulary acquisition (in python/ankistuff of the current repository)
Resulting deck are available here:
http://amadio71.free.fr/strongsankistuff/
